import { Roboto_Mono } from 'next/font/google';
import './globals.css';

// const font = Roboto_Mono({ subsets: ['latin'] });

export const metadata = {
  title: '404Hz',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body>{children}</body>
    </html>
  );
}
